### ISSUE TITLE
kafka监控程序运行报错

### ISSUE THREAD

**Issue by zczczc2018** [TurboWay/spiderman#12]
Traceback (most recent call last):
  File "C:\Users\chengzhang\AppData\Local\Programs\Python\Python39\lib\site-packages\kafka\consumer\fetcher.py", line 445, in _message_generator
    raise StopIteration('Subscription needs partition assignment')
StopIteration: Subscription needs partition assignment

是consumer.subscribe()需要别的参数吗，我看运行实例图片上也只有topics=['zhifang',]这一个参数

**Comment by TurboWay** [comment]
应该不需要。每个 kafka 主题都至少会有一个分区，这个看起来像是 kafka 的环境问题，可以运行下 kafka 命令，看是否可以正常消费
```shell
kafka-console-consumer --bootstrap-server your-kafka-broker:9092 --topic zhifang --from-beginning
```

**Comment by zczczc2018** [comment]
经过调整，kafka已经可以正常生产消费消息了，但是代码运行依旧报错

![image](https://user-images.githubusercontent.com/48899949/112935596-a405f180-9156-11eb-8c05-1da34baba7bb.png)

**Comment by TurboWay** [comment]
更新一下 kafka-python 包试试
```
pip uninstall kafka
pip install kafka-python
```

**Comment by zczczc2018** [comment]
我使用的是python3.9的环境，kafka-1.3.5的版本，重新安装以后出现了**return '<SimpleProducer batch=%s>' % self.async**的语法错误，之前我把源码里面的async全都替换为async_了，运行报错就是**StopIteration: Subscription needs partition assignment**。

**Comment by TurboWay** [comment]
> 我使用的是python3.9的环境，kafka-1.3.5的版本，重新安装以后出现了**return '' % self.async**的语法错误，之前我把源码里面的async全都替换为async_了，运行报错就是**StopIteration: Subscription needs partition assignment**。

建议按如上命令，直接升级一下 kafka-python，再进行测试

**Comment by zczczc2018** [comment]
昨天kafka配置又出现了问题，改了一下，现在使用kafka-python已经可以用了，非常感谢！
