### ISSUE TITLE
有个问题请教大佬

### ISSUE THREAD

**Issue by jiamianguigui** [TurboWay/spiderman#14]
如果删去程序部分功能，如kafka那块的功能，会影响到整体运行吗

**Comment by TurboWay** [comment]
不会影响，所有的入库操作都是通过管道来实现的，可以直接拔插，只要 spider 文件中，不启用就行了

**Comment by jiamianguigui** [comment]
好的，谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月31日(星期三) 上午10:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TurboWay/spiderman] 有个问题请教大佬 (#14)





 
不会影响，所有的入库操作都是通过管道来实现的，可以直接拔插，只要 spider 文件中，不启用就行了
