### ISSUE TITLE
  分布式模式下INFO信息有误

### ISSUE THREAD

**Issue by zczczc2018** [TurboWay/spiderman#15]
我配置了一台Slave，爬取结果是成功的，但是在Pycharm的console里输出一直是slave:localhost.localdomain爬虫执行成功，调试的时候连接的SSH的hostname确实是我配置的slave 的host，但是msg_out却是localhost，为什么呢

**Comment by TurboWay** [comment]
在你的 slave 执行以下命令，看下输出结果
```shell
hostname
```
应该是你的 slave 机器没有自定义 hostname

**Comment by zczczc2018** [comment]
是的，是这个问题，改完就好了，谢谢！
