### ISSUE TITLE
demo 运行没爬到东西

### ISSUE THREAD

**Issue by donneyluck** [TurboWay/spiderman#35]
![image](https://user-images.githubusercontent.com/122257591/217756282-73c5d8b8-6b6e-4dd6-8a77-b4d94c20bbf6.png)

查过日志和代码     
启动可以正常加入 redis  start url

但是启动爬虫后  貌似没有执行 make_request_from_data  这个函数不会进  麻烦大佬拯救一下
于是乎 什么都没有爬到

另外  无论用不用虚拟环境   requirements.txt  安装环境都会报错 

python 3.10   
linux manjaro
执行命令  python SP_JOBS/zhifang_job.py

**Comment by TurboWay** [comment]
这个测试demo的目标网站改版了，所以没有解析到数据。回头我在更新下代码。

**Comment by TurboWay** [comment]
已修正 [e0beefed67ad8408acf4cdb007b9b3beb6b61d8d](https://github.com/TurboWay/spiderman/commit/e0beefed67ad8408acf4cdb007b9b3beb6b61d8d)

> 这个测试demo的目标网站改版了，所以没有解析到数据。回头我在更新下代码。

**Comment by donneyluck** [comment]
跑了最新的代码  目前没发现什么问题  感谢大佬解答
