### ISSUE TITLE
关于cookies使用的问题

### ISSUE THREAD

**Issue by donneyluck** [TurboWay/spiderman#40]
问题：  在学习爬取steam的过程中 遇到了年龄验证的问题  查询解决方案是使用 cookies
             发现在框架中 配置了好像没什么效果  是我的格式有问题吗？ 
![image](https://user-images.githubusercontent.com/122257591/218911993-ec6a4ad4-8fff-416b-ae54-f0ed3a8ef431.png)

**Comment by TurboWay** [comment]
需要使用字符串格式，不是用dict
```python
self.cookies = (
            # 多账号采集的话，可以在这边定制多个 cookie string
            'BAIDUID=D59023F6ABEFB4A60F019E08C58586D2:FG=1; BD_UPN=12314753;BD_CK_SAM=1'
        )
```

**Comment by donneyluck** [comment]
起因  学习尝试爬取steam游戏   但是会返回年龄验证页面    经过查询学习尝试了如下方案
1. 设置cookies  失败
![image](https://user-images.githubusercontent.com/122257591/218991070-350b41e5-0099-423c-a801-da49b609446f.png)
![image](https://user-images.githubusercontent.com/122257591/218991171-4f67ee24-96fa-4b62-88d2-a3bd6b94d47a.png)

2. 通过post请求绕过年龄验证 失败
![image](https://user-images.githubusercontent.com/122257591/218991654-11f4331e-8ace-4e03-ac7c-7c74c8beb8b3.png)
发送后 回包页面依然是年龄验证
![image](https://user-images.githubusercontent.com/122257591/218991773-6a885099-ef88-4bee-b855-50cef1b5b906.png)

3.通过selenium模拟点击 会真实拉起游览器  感觉效率低 而且不会用

代码在下面 是根据框架模板生成的3个文件  麻烦抽时间指点一下 万分感谢

[code.zip](https://github.com/TurboWay/spiderman/files/10741585/code.zip)

**Comment by TurboWay** [comment]
该问题与本项目无关，请自行研究。
