### ISSUE TITLE
elasticsearch 过期了。可以更新一下么，谢谢

### ISSUE THREAD

**Issue by xkungfu** [TurboWay/spiderman#7]

**Comment by TurboWay** [comment]
过期是什么意思？

**Comment by xkungfu** [comment]
tablename对应的是_type, _type在新版里应该是取消了。

**Comment by TurboWay** [comment]
[https://github.com/TurboWay/spiderman/commit/2a92f4e09c95babe410f4e87f2ef762213e4a66e](https://github.com/TurboWay/spiderman/commit/2a92f4e09c95babe410f4e87f2ef762213e4a66e)
